### ISSUE TITLE
v2.2.0: Cache path broken for Ubuntu

### ISSUE THREAD

**Issue by hugovk** [hynek/setup-cached-uv#17]
The devguide docs build passed on `main` two days ago, on Ubuntu:

https://github.com/python/devguide/actions/runs/10666808924

Here's a devguide docs build of `main`, failing today:

```
/home/runner/work/devguide/devguide/"/tmp/scu-uv-cache"/archive-v0/LZw1MOw0z-Porf5QiCanY/sphinx-8.0.2.dist-info/LICENSE.rst:55: WARNING: Inline literal start-string without end-string. [docutils]
/home/runner/work/devguide/devguide/"/tmp/scu-uv-cache"/archive-v0/LZw1MOw0z-Porf5QiCanY/sphinx-8.0.2.dist-info/LICENSE.rst:67: ERROR: Document may not end with a transition. [docutils]
```

https://github.com/python/devguide/actions/runs/10770128668/job/29862846750#step:5:85

That cache path looks broken, I think it should be an absolute `/tmp/scu-uv-cache` path instead of a local one. This causes our tooling to check for RST errors in files in the cache, which we don't care about.

Here's a passing build today, but pinning to v2.1.0 of the action:

https://github.com/hugovk/devguide/actions/runs/10770299577

**Comment by hynek** [comment]
v2.2.1 is tagged

**Comment by hugovk** [comment]
Thanks, confirmed working again with `@v2`!
