### ISSUE TITLE
Default for `cache-dependency-path`?

### ISSUE THREAD

**Issue by hugovk** [hynek/setup-cached-uv#19]
Like `actions/setup-python` with `cache: pip`, would it be sensible or feasible for the action to default to `requirements.txt` / `pyproject.toml`?

https://github.com/actions/setup-python#caching-packages-dependencies says:

> The action defaults to searching for a dependency file (`requirements.txt` or `pyproject.toml` for pip, `Pipfile.lock` for pipenv or `poetry.lock` for poetry) in the repository, and uses its hash as a part of the cache key. Input `cache-dependency-path` is used for cases when multiple dependency files are used, they are located in different subdirectories or different files for the hash that want to be used.

**Comment by hynek** [comment]
Hm yeah, as an additional, but not sufficient cache buster, huh? 🤔 The docs only seem to consider it as the all-or-nothing, but it could be another factor.

I would say the only sensible & un-surprising default would be `pyproject.toml`. Maybe we can add `uv.lock` auto-detection once they get more prevalent later.

**Comment by hugovk** [comment]
> I would say the only sensible & un-surprising default would be `pyproject.toml`. Maybe we can add `uv.lock` auto-detection once they get more prevalent later.

Sounds good, https://github.com/hynek/setup-cached-uv/pull/20 sets it to `pyproject.toml`.

**Comment by hynek** [comment]
live in https://github.com/hynek/setup-cached-uv/releases/tag/v2.3.0
